"""
Build regulations.db from the canonical JSON export.
Safe to re-run — drops and recreates the table each time.

    python seed_regulations.py

NOTE: Records 34-45 (out of 45 total) were not captured in the source JSON
      due to message truncation. Paste them into RECORDS below and re-run.
"""

import os
import sqlite3

DB_PATH = os.path.join(os.path.dirname(__file__), "regulations.db")

SCHEMA_SQL = """
DROP TABLE IF EXISTS regulations;
CREATE TABLE regulations (
    id                    INTEGER PRIMARY KEY,
    region                TEXT,
    jurisdiction          TEXT,
    type                  TEXT,
    county                TEXT,
    program_name          TEXT,
    reg_type              TEXT,
    code_citation         TEXT,
    adopted_effective     TEXT,
    mandatory             TEXT,
    trigger_scope         TEXT,
    threshold             TEXT,
    project_types_covered TEXT,
    on_site_rate          TEXT,
    in_lieu_rate          TEXT,
    fee_cap               TEXT,
    compliance_options    TEXT,
    exemptions            TEXT,
    administrator_fund    TEXT,
    layered_with          TEXT,
    source_url            TEXT,
    date_verified         TEXT,
    currency_risk_flags   TEXT,
    confidence            TEXT,
    notes                 TEXT
);
CREATE INDEX idx_region       ON regulations(region);
CREATE INDEX idx_jurisdiction ON regulations(jurisdiction);
CREATE INDEX idx_mandatory    ON regulations(mandatory);
CREATE INDEX idx_reg_type     ON regulations(reg_type);
"""

COLUMNS = [
    "id", "region", "jurisdiction", "type", "county", "program_name",
    "reg_type", "code_citation", "adopted_effective", "mandatory",
    "trigger_scope", "threshold", "project_types_covered", "on_site_rate",
    "in_lieu_rate", "fee_cap", "compliance_options", "exemptions",
    "administrator_fund", "layered_with", "source_url", "date_verified",
    "currency_risk_flags", "confidence", "notes",
]

RECORDS = [
    {
        "id": 1,
        "region": "State-wide",
        "jurisdiction": "California (statewide)",
        "type": "state",
        "county": None,
        "program_name": "CEQA cultural resources mitigation",
        "reg_type": "S",
        "code_citation": "Public Resources Code § 21000 et seq.; CEQA Guidelines § 15064.5",
        "adopted_effective": "1970 (PRC); guidelines updated periodically",
        "mandatory": "Yes (project-specific)",
        "trigger_scope": "Both",
        "threshold": "EIR-triggering projects affecting historical/cultural resources",
        "project_types_covered": "Any project requiring CEQA review with cultural-resource impacts",
        "on_site_rate": "Project-specific",
        "in_lieu_rate": "Project-specific",
        "fee_cap": None,
        "compliance_options": "Avoidance, preservation in place, recordation, interpretive programs",
        "exemptions": "Categorical exemptions per CEQA Guidelines",
        "administrator_fund": "Lead agency (varies by project)",
        "layered_with": "Type 3 Specific Plans, Type 4 CBAs",
        "source_url": "leginfo.legislature.ca.gov",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Guidelines periodically updated",
        "confidence": "Settled law / state code",
        "notes": "Often triggers commissioned interpretive art, public history installations, or contribution to museums as mitigation for impacts on archaeological, historical, or tribal cultural resources.",
    },
    {
        "id": 2,
        "region": "State-wide",
        "jurisdiction": "California (statewide)",
        "type": "state",
        "county": None,
        "program_name": "California Density Bonus Law",
        "reg_type": "S",
        "code_citation": "Government Code § 65915",
        "adopted_effective": "1979; amended many times",
        "mandatory": "Conditional (developer election)",
        "trigger_scope": "Private development",
        "threshold": "Projects offering affordable housing or other qualifying benefits",
        "project_types_covered": "Residential and mixed-use density bonus seekers",
        "on_site_rate": None,
        "in_lieu_rate": None,
        "fee_cap": None,
        "compliance_options": "Affordable units, child care, senior housing, etc.",
        "exemptions": None,
        "administrator_fund": "Local jurisdiction implementation",
        "layered_with": "Local Type 5 implementations (TOC, CHIP, etc.)",
        "source_url": "leginfo.legislature.ca.gov",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Frequently amended",
        "confidence": "Settled law / state code",
        "notes": "Affordability-focused. Cultural facilities CAN appear as eligible community benefits in some local implementations but are not state-mandated.",
    },
    {
        "id": 3,
        "region": "State-wide",
        "jurisdiction": "California (statewide)",
        "type": "state",
        "county": None,
        "program_name": "Ehrlich v. City of Culver City (1996)",
        "reg_type": "S",
        "code_citation": "12 Cal. 4th 854",
        "adopted_effective": "1996 (Cal. Supreme Court)",
        "mandatory": "Precedent",
        "trigger_scope": None,
        "threshold": None,
        "project_types_covered": None,
        "on_site_rate": None,
        "in_lieu_rate": None,
        "fee_cap": None,
        "compliance_options": None,
        "exemptions": None,
        "administrator_fund": "California Supreme Court",
        "layered_with": "Foundational for all CA percent-for-art ordinances",
        "source_url": "Westlaw / Justia / California Supreme Court opinions",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Settled law",
        "confidence": "Settled law / state code",
        "notes": "Validates public art requirements as legitimate police-power land use regulation, not Takings-clause exaction. Underpins legal defensibility of every percent-for-art ordinance in CA.",
    },
    {
        "id": 4,
        "region": "State-wide",
        "jurisdiction": "California (statewide)",
        "type": "state",
        "county": None,
        "program_name": "Mitigation Fee Act (AB 1600)",
        "reg_type": "S",
        "code_citation": "Government Code §§ 66000–66025",
        "adopted_effective": "1987 (AB 1600)",
        "mandatory": "Yes (procedural framework)",
        "trigger_scope": "Both",
        "threshold": None,
        "project_types_covered": "Any local fee on new development",
        "on_site_rate": None,
        "in_lieu_rate": None,
        "fee_cap": None,
        "compliance_options": None,
        "exemptions": None,
        "administrator_fund": "Local jurisdiction",
        "layered_with": "All Type 1 in-lieu fee mechanisms",
        "source_url": "leginfo.legislature.ca.gov",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Amended periodically",
        "confidence": "Settled law / state code",
        "notes": "Provides the nexus framework that enables percent-for-art in-lieu fees. Requires fees to demonstrate reasonable relationship between fee amount and impact mitigated. Foundational procedural law.",
    },
    {
        "id": 5,
        "region": "State-wide",
        "jurisdiction": "California (statewide)",
        "type": "state",
        "county": None,
        "program_name": "Proposition 28 — Arts and Music in Schools",
        "reg_type": "S",
        "code_citation": "California Constitution Article XVI § 8.5",
        "adopted_effective": "Passed November 2022",
        "mandatory": "Yes (constitutional)",
        "trigger_scope": "K-12 education funding",
        "threshold": None,
        "project_types_covered": "All public K-12 schools",
        "on_site_rate": None,
        "in_lieu_rate": None,
        "fee_cap": None,
        "compliance_options": None,
        "exemptions": None,
        "administrator_fund": "California Department of Education",
        "layered_with": "K-12 districts (separate ecosystem)",
        "source_url": "leginfo.legislature.ca.gov",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Implementation ongoing",
        "confidence": "Settled law / state code",
        "notes": "Approximately $1B/year for K-12 arts/music. NOT a development-triggered mechanism. Captured here for completeness of CA arts-funding ecosystem; not relevant to development-side lead generation.",
    },
    {
        "id": 6,
        "region": "State-wide",
        "jurisdiction": "California (statewide)",
        "type": "state",
        "county": None,
        "program_name": "Redevelopment Agency dissolution",
        "reg_type": "S",
        "code_citation": "AB X1 26 (2011); AB 1484 (2012); Health & Safety Code § 34170 et seq.",
        "adopted_effective": "Effective February 1, 2012",
        "mandatory": "Yes (state mandate)",
        "trigger_scope": None,
        "threshold": None,
        "project_types_covered": "All former RDAs and successor agencies",
        "on_site_rate": None,
        "in_lieu_rate": None,
        "fee_cap": None,
        "compliance_options": None,
        "exemptions": None,
        "administrator_fund": "Successor agencies, DOF oversight",
        "layered_with": "All Type 6 redevelopment legacy obligations",
        "source_url": "leginfo.legislature.ca.gov",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Implementation disputes ongoing",
        "confidence": "Settled law / state code",
        "notes": "Dissolved all CA Redevelopment Agencies. CRA/LA was largest (~$750M budget). Pre-dissolution RDAs typically had 1% public art on RDA-funded projects. Legacy: Art Covenants on properties in former RDA areas; transferred trust fund balances; unresolved successor obligations.",
    },
    {
        "id": 7,
        "region": "City of LA",
        "jurisdiction": "City of Los Angeles",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "Arts Development Fee (ADF) — Private Arts Development Fee Program",
        "reg_type": "1",
        "code_citation": "LAMC § 91.107",
        "adopted_effective": "1991",
        "mandatory": "Yes",
        "trigger_scope": "Private development",
        "threshold": "Building permit valuation $500,000 or more",
        "project_types_covered": "Commercial, industrial, mixed-use, multi-family residential",
        "on_site_rate": "1% (lower of 1% or sqft-based fee)",
        "in_lieu_rate": "Same — fee paid to Cultural Affairs Trust Fund",
        "fee_cap": "None",
        "compliance_options": "On-site art OR in-lieu fee (developer election); architecture-as-art allowed in limited circumstances",
        "exemptions": "Affordable housing, religious, some public agencies",
        "administrator_fund": "LA Department of Cultural Affairs (DCA) — Cultural Affairs Trust Fund",
        "layered_with": "Type 3 Specific Plans (Warner Center, CASP, DTLA 2040, Hollywood CPIO); Type 6 CRA legacy in former CRA areas",
        "source_url": "https://culture.lacity.gov/percent-public-art",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Stable",
        "confidence": "Confirmed by code",
        "notes": "The canonical LA citywide ordinance. 'Lower of 1% or sqft-based fee' is distinctive — developers pay the smaller of two calculations. Andrew's prior recollection of $5M threshold was incorrect; the threshold is $500K.",
    },
    {
        "id": 8,
        "region": "City of LA",
        "jurisdiction": "City of Los Angeles",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "CRA/LA Art Covenants (legacy)",
        "reg_type": "6",
        "code_citation": "Pre-2012 CRA/LA project area covenants; assigned to City of LA upon dissolution",
        "adopted_effective": "Pre-2012; binding obligations continuing",
        "mandatory": "Yes (recorded covenants)",
        "trigger_scope": "Current property owners in former CRA areas",
        "threshold": "Properties subject to recorded Art Covenants",
        "project_types_covered": "Properties in former CRA project areas (Bunker Hill, Hollywood, North Hollywood, etc.)",
        "on_site_rate": "Per individual covenant",
        "in_lieu_rate": None,
        "fee_cap": None,
        "compliance_options": "Maintain covenanted art; deaccession requires City review",
        "exemptions": None,
        "administrator_fund": "City of LA (via DCA, post-CRA assignment)",
        "layered_with": "Any development in former CRA project areas",
        "source_url": "https://cityclerk.lacity.org/onlinedocs/2019/19-0186_rpt_CAO_02-28-2019.pdf",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Title-level diligence required",
        "confidence": "Open item — pending",
        "notes": "Critical due diligence item for buyers/operators in former CRA areas. Approximately $5.26M trust fund balance transferred from CRA/LA to DCA in 2019.",
    },
    {
        "id": 9,
        "region": "City of LA",
        "jurisdiction": "City of Los Angeles",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "Cornfield Arroyo Seco Specific Plan (CASP)",
        "reg_type": "3",
        "code_citation": "Ord. 182,617 (2013); LAMC 13B.4; LA Admin Code Ch. 160; CASP Update adopted 2024 (NOD 11/13/2024)",
        "adopted_effective": "Original 2013; Update adopted 2024",
        "mandatory": "Conditional (developer election for additional FAR)",
        "trigger_scope": "Private development",
        "threshold": "Projects seeking additional floor area beyond base zoning",
        "project_types_covered": "Private development in CASP boundaries (660 acres NE LA — Lincoln Heights, Chinatown area, Cypress Park)",
        "on_site_rate": "Per Community Benefits Program menu (post-2024)",
        "in_lieu_rate": "Original: Floor Area Payment to Trust Fund (rescinded by 2024 update); New CBP replaces it",
        "fee_cap": None,
        "compliance_options": "(Post-2024) New Community Benefits Program — publicly accessible open space, community facilities, etc.",
        "exemptions": "Per plan text",
        "administrator_fund": "City Clerk's Office (original Trust Fund); successor under CBP",
        "layered_with": "Citywide ADF still applies in addition to CASP",
        "source_url": "https://planning.lacity.gov/plans-policies/casp-update",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "MAJOR CHANGE — original Floor Area Payment Trust Fund RESCINDED by 2024 update; new CBP details still being implemented",
        "confidence": "Open item — pending",
        "notes": "Different model than percent-for-art — historically community benefits via floor-area payment. Public art was one of many eligible 'River Public Benefits' categories. The 2024 update represents a regulatory pivot toward menu-based community benefits.",
    },
    {
        "id": 10,
        "region": "City of LA",
        "jurisdiction": "City of Los Angeles",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "DTLA 2040 / Downtown Community Plan — Community Benefits Program",
        "reg_type": "3",
        "code_citation": "Combines Central City + Central City North Community Plans; Council File 22-0617; approved 2023",
        "adopted_effective": "Council approval 2023; implementing ordinances finalizing",
        "mandatory": "Conditional (for projects seeking density bonuses)",
        "trigger_scope": "Private development",
        "threshold": "Projects seeking density bonuses across 10 submarkets",
        "project_types_covered": "Private development in DTLA 2040 plan area (entirety of Central City + Central City North)",
        "on_site_rate": "Per CBP menu",
        "in_lieu_rate": "Per CBP menu",
        "fee_cap": None,
        "compliance_options": "REQUIRED: on-site affordable housing. OPTIONAL menu: public open space, community facilities (health clinics, childcare, possibly cultural)",
        "exemptions": "Per implementing ordinances",
        "administrator_fund": "LA City Planning + DCA + successor agencies",
        "layered_with": "Citywide ADF + potential CRA-era Art Covenants",
        "source_url": "Council File 22-0617",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Implementing ordinances still being finalized — menu items for arts to confirm",
        "confidence": "Open item — pending",
        "notes": "Replaced prior TFAR (Transfer of Floor Area Rights) program, which had funneled most fees to streetcar and Pershing Square. Whether cultural facilities are explicit menu items vs. folded into 'community facilities' will be clear once implementing ordinances finalize.",
    },
    {
        "id": 11,
        "region": "City of LA",
        "jurisdiction": "City of Los Angeles",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "Downtown Art in Public Places (legacy CRA, status uncertain)",
        "reg_type": "6",
        "code_citation": "Pre-2012 CRA program — current post-dissolution status unclear",
        "adopted_effective": "Pre-2012; status uncertain post-dissolution",
        "mandatory": "Status to verify",
        "trigger_scope": "Private development in former Downtown CRA area",
        "threshold": "Historically 1% of private development costs in downtown CRA area",
        "project_types_covered": "Properties in former downtown CRA area",
        "on_site_rate": "Historically 1%",
        "in_lieu_rate": "Historically 1%",
        "fee_cap": None,
        "compliance_options": None,
        "exemptions": None,
        "administrator_fund": "Historically CRA/LA; now uncertain",
        "layered_with": "Was parallel to citywide ADF — current status uncertain",
        "source_url": "DCA verification needed",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "STATUS UNCLEAR — needs direct DCA verification",
        "confidence": "Open item — pending",
        "notes": "Possible source of Andrew's prior memory of a separate downtown layer. Whether this requirement persists for new development or was rescinded with RDA dissolution requires direct verification.",
    },
    {
        "id": 12,
        "region": "City of LA",
        "jurisdiction": "City of Los Angeles",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "Hollywood Community Plan + CPIO Community Benefits",
        "reg_type": "3",
        "code_citation": "Hollywood Community Plan updated January 2025; CPIO subarea-based checklists",
        "adopted_effective": "Most recent update January 2025",
        "mandatory": "Conditional (for entitlements seeking density)",
        "trigger_scope": "Private development",
        "threshold": "Per subarea (Regional Center, Corridors, Multi-Family Residential, Character Residential)",
        "project_types_covered": "Development in Hollywood community plan area seeking specific entitlements",
        "on_site_rate": "Per CPIO checklist",
        "in_lieu_rate": "Per CPIO checklist",
        "fee_cap": None,
        "compliance_options": "Menu-style benefits by subarea",
        "exemptions": "Per CPIO",
        "administrator_fund": "LA City Planning",
        "layered_with": "Citywide ADF; potential CRA-era covenants",
        "source_url": "https://planning.lacity.gov/plans-policies/community-plan-area/hollywood",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Recently updated (Jan 2025); CPIO checklists evolving",
        "confidence": "Open item — pending",
        "notes": "Need follow-up to identify specific arts-related menu options in each subarea CPIO checklist.",
    },
    {
        "id": 13,
        "region": "City of LA",
        "jurisdiction": "City of Los Angeles",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "LAX / LAWA Public Art Program",
        "reg_type": "3",
        "code_citation": "LAX Specific Plan; LAWA internal policy",
        "adopted_effective": "Ongoing (project-by-project)",
        "mandatory": "Internal LAWA policy",
        "trigger_scope": "Public CIP (LAWA capital projects)",
        "threshold": "Major LAX capital projects",
        "project_types_covered": "LAX terminals, automated people mover, terminal expansions",
        "on_site_rate": "Project-specific",
        "in_lieu_rate": None,
        "fee_cap": None,
        "compliance_options": "Commissioned public art integrated into capital projects",
        "exemptions": "Per LAWA policy",
        "administrator_fund": "Los Angeles World Airports (LAWA)",
        "layered_with": "Operates separately from DCA citywide programs",
        "source_url": "lawa.org",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Structure not fully extracted via web search",
        "confidence": "Open item — pending",
        "notes": "More capital-project-driven than developer-triggered. Concessionaire and tenant development may have separate art expectations — to verify directly with LAWA.",
    },
    {
        "id": 14,
        "region": "City of LA",
        "jurisdiction": "City of Los Angeles",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "Public Works Improvements Arts Program (PWIAP)",
        "reg_type": "1",
        "code_citation": "City policy (since 1988)",
        "adopted_effective": "1988",
        "mandatory": "Yes",
        "trigger_scope": "Public CIP",
        "threshold": "City-funded construction/improvement/renovation projects",
        "project_types_covered": "All eligible City capital projects",
        "on_site_rate": "1% of total project cost set aside for public art",
        "in_lieu_rate": None,
        "fee_cap": "None",
        "compliance_options": "Commissioned public art on or near project site",
        "exemptions": "Project-by-project per DCA review",
        "administrator_fund": "LA Department of Cultural Affairs",
        "layered_with": "Public capital improvement program",
        "source_url": "https://culture.lacity.gov/percent-public-art",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Stable",
        "confidence": "Confirmed by code",
        "notes": "Public-sector companion to ADF. Predates the private-side ADF by three years.",
    },
    {
        "id": 15,
        "region": "City of LA",
        "jurisdiction": "City of Los Angeles",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "STAPLES Center / LA Live CBA (landmark example)",
        "reg_type": "4",
        "code_citation": "Private agreement; AEG developer; Figueroa Corridor Coalition (30+ orgs)",
        "adopted_effective": "2001",
        "mandatory": "Contractual",
        "trigger_scope": "Project-specific (precedent)",
        "threshold": None,
        "project_types_covered": "Large discretionary entitlements",
        "on_site_rate": None,
        "in_lieu_rate": None,
        "fee_cap": None,
        "compliance_options": "Negotiated benefits package",
        "exemptions": None,
        "administrator_fund": "Per agreement",
        "layered_with": "On top of any Type 1/3 requirements",
        "source_url": "(historical project record)",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Precedent only",
        "confidence": "Confirmed by city page",
        "notes": "First comprehensive CBA in the US. ~$150M total benefits package; arts components secondary to housing/wages. LA has NO citywide Community Benefits Ordinance — CBAs are per-project.",
    },
    {
        "id": 16,
        "region": "City of LA",
        "jurisdiction": "City of Los Angeles",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "Transit Oriented Communities (TOC) Incentive Program",
        "reg_type": "5",
        "code_citation": "LAMC § 12.22 A.31; Measure JJJ (2016); effective 9/22/2017",
        "adopted_effective": "Measure JJJ 2016; effective 9/22/2017",
        "mandatory": "Conditional (developer election)",
        "trigger_scope": "Private development",
        "threshold": "Projects within 0.5 miles of major transit stops",
        "project_types_covered": "Residential and mixed-use seeking density bonuses",
        "on_site_rate": None,
        "in_lieu_rate": None,
        "fee_cap": None,
        "compliance_options": "On-site affordable units in exchange for density/parking incentives",
        "exemptions": None,
        "administrator_fund": "LA City Planning",
        "layered_with": "Note: Fix the City v. LA (2022) confirmed Specific Plans SUPERSEDE TOC in conflicts",
        "source_url": "https://planning.lacity.gov/plans-policies/transit-oriented-communities-incentive-program",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Affordability-focused; not arts-specific",
        "confidence": "Confirmed by code",
        "notes": "Affordability-focused with NO direct arts components. Captured to make clear that LA's primary density-bonus program does not create an arts hook.",
    },
    {
        "id": 17,
        "region": "City of LA",
        "jurisdiction": "City of Los Angeles",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "Warner Center 2035 Cultural Amenities Fee",
        "reg_type": "3",
        "code_citation": "WC 2035 Specific Plan (Ord. 182,766); Section 9.5; LA Admin Code Ch. 164; Ord. 184,838",
        "adopted_effective": "Plan effective 12/25/2013; Trust Fund codified subsequently",
        "mandatory": "Yes",
        "trigger_scope": "Private development",
        "threshold": "Permit valuation $500,000 or more (per Project Permit Checklist)",
        "project_types_covered": "All private development in WC 2035 Specific Plan boundaries (~1,100 acres in Woodland Hills)",
        "on_site_rate": "On-site art conveyance allowed",
        "in_lieu_rate": "Cultural Amenities Fee paid to Trust Fund 577 (rate per sqft to verify in Specific Plan)",
        "fee_cap": "Not surfaced",
        "compliance_options": "On-site public art (recorded with City Planning) OR fee to Warner Center Cultural Amenities Trust Fund (Fund 577)",
        "exemptions": "Per Specific Plan text",
        "administrator_fund": "Warner Center Cultural Amenities Committee (Section 9.5); WC 2035 Plan Implementation Board",
        "layered_with": "STACKS WITH citywide ADF (LAMC § 91.107)",
        "source_url": "https://planning.lacity.gov/plans-policies/warner-center-2035-cultural-amenity-plan",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Specific Plan rate per sqft to verify",
        "confidence": "Open item — pending",
        "notes": "Stacks on top of citywide ADF — Warner Center projects at $500K+ face BOTH fees. Recent application: CF 25-1186 (January 2026).",
    },
    {
        "id": 18,
        "region": "LA County",
        "jurisdiction": "Los Angeles County (unincorporated)",
        "type": "county",
        "county": "Los Angeles",
        "program_name": "Civic Art Policy (public CIP)",
        "reg_type": "1",
        "code_citation": "LA County Civic Art Policy (Board of Supervisors, 2004)",
        "adopted_effective": "2004",
        "mandatory": "Yes",
        "trigger_scope": "Public CIP",
        "threshold": "All County-funded capital projects",
        "project_types_covered": "County buildings, parks, infrastructure",
        "on_site_rate": "1% of County design and construction costs",
        "in_lieu_rate": None,
        "fee_cap": None,
        "compliance_options": "Commissioned civic artworks",
        "exemptions": "Per Civic Art Program review",
        "administrator_fund": "LA County Department of Arts and Culture — Civic Art Special Fund",
        "layered_with": "Public capital improvement program",
        "source_url": "https://www.lacountyarts.org/experiences/civic-art",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Stable",
        "confidence": "Confirmed by city page",
        "notes": "Public-sector companion to PAPD. Applies countywide to County-funded projects.",
    },
    {
        "id": 19,
        "region": "LA County",
        "jurisdiction": "Los Angeles County (unincorporated)",
        "type": "county",
        "county": "Los Angeles",
        "program_name": "Public Art in Private Development (PAPD)",
        "reg_type": "1",
        "code_citation": "Title 22 § 22.246; adopted by Board of Supervisors 9/15/2021",
        "adopted_effective": "Adopted 9/15/2021",
        "mandatory": "Yes",
        "trigger_scope": "Private development",
        "threshold": "Building valuation $903,902 or more (CPI-indexed; current as of 7/1/2025)",
        "project_types_covered": "Commercial, industrial, residential, mixed-use",
        "on_site_rate": "1% of building valuation",
        "in_lieu_rate": "1% of building valuation to Public Art in Private Development Fund",
        "fee_cap": "None",
        "compliance_options": "Commissioned artwork (on-site), conservation/restoration, artistic and cultural services, cultural facility (5-mile radius eligible), in-lieu fee",
        "exemptions": "Affordable housing; residential ≤29 dwelling units; performing arts/museum spaces; ADA/seismic remediation",
        "administrator_fund": "LA County Department of Arts and Culture; Public Art in Private Development Fund",
        "layered_with": "Applies in unincorporated LA County only (not within incorporated cities)",
        "source_url": "https://www.lacountyarts.org/experiences/civic-art/public-art-private-development-papd-ordinance",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Threshold CPI-indexed annually — verify current threshold each year",
        "confidence": "Confirmed by code",
        "notes": "First public art in private development ordinance for LA County itself. Broader than typical ordinances — funds can support not just sculpture but arts programming, cultural facilities, and conservation projects. The 5-mile radius eligibility for cultural facilities is distinctive.",
    },
    {
        "id": 20,
        "region": "LA County core",
        "jurisdiction": "Beverly Hills",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "Fine Art Ordinance (Article 8)",
        "reg_type": "2",
        "code_citation": "BHMC § 3-1-801 et seq.; Ord. 15-O-2672 (2/6/2015)",
        "adopted_effective": "2/6/2015",
        "mandatory": "Yes",
        "trigger_scope": "Private development",
        "threshold": "Project cost $500,000+ (commercial/industrial/mixed-use only; residential excluded)",
        "project_types_covered": "Commercial, industrial, mixed-use",
        "on_site_rate": "Tier 1 ($500K–$1M): 1%; Tier 2 (>$1M): 1% on first $1M + 1.5% above",
        "in_lieu_rate": "90% of on-site value",
        "fee_cap": "None",
        "compliance_options": "On-site fine art OR in-lieu fee (at 90% of on-site value as discount)",
        "exemptions": "Residential projects entirely excluded",
        "administrator_fund": "Beverly Hills Fine Art Commission",
        "layered_with": None,
        "source_url": "qcode.us / beverlyhills.org",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Stable",
        "confidence": "Confirmed by code",
        "notes": "TIERED RATE structure — escalates above $1M. Fund balance ~$2.65M as of early 2025. Residential exclusion is notable.",
    },
    {
        "id": 21,
        "region": "LA County core",
        "jurisdiction": "Burbank",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "Art in Public Places (AIPP)",
        "reg_type": "1",
        "code_citation": "BMC § 10-1-1114; original May 1992; amended Ord. 24-4 (Hollywood Burbank Airport post-security areas)",
        "adopted_effective": "Original May 1992",
        "mandatory": "Yes",
        "trigger_scope": "Private development",
        "threshold": "$500,000+ construction budget",
        "project_types_covered": "Commercial, industrial, mixed-use, residential (per code)",
        "on_site_rate": "1%",
        "in_lieu_rate": "1% to Art in Public Places Fund",
        "fee_cap": "None",
        "compliance_options": "On-site OR in-lieu; exterior siting minimum required",
        "exemptions": "Per code",
        "administrator_fund": "Burbank Art in Public Places Committee",
        "layered_with": "Airport-specific zone (Hollywood Burbank post-security)",
        "source_url": "burbankca.gov municipal code",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Recent amendment 24-4 expanded to airport post-security areas",
        "confidence": "Confirmed by city page",
        "notes": "Mature program — 130+ pieces produced since 1992. Exterior siting minimum requirement is distinctive. Ord. 24-4 extended to Hollywood Burbank Airport post-security areas.",
    },
    {
        "id": 22,
        "region": "LA County core",
        "jurisdiction": "Culver City",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "Art in Public Places Program (APPP)",
        "reg_type": "1",
        "code_citation": "CCMC § 15.06.100",
        "adopted_effective": "1988",
        "mandatory": "Yes",
        "trigger_scope": "Private development",
        "threshold": "Residential 5+ units; new commercial/industrial $500K+; remodel commercial/industrial $250K+",
        "project_types_covered": "Commercial, industrial, residential 5+ units",
        "on_site_rate": "1% of building valuation",
        "in_lieu_rate": "1% (mandatory if allocation <$75K)",
        "fee_cap": "None",
        "compliance_options": "On-site art OR in-lieu fee; allows architecture-as-art",
        "exemptions": "Standard exemptions per Code",
        "administrator_fund": "Culver City Public Art and Historic Preservation",
        "layered_with": None,
        "source_url": "culvercity.org municipal code",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Stable",
        "confidence": "Confirmed by code",
        "notes": "Subject of foundational case law — Ehrlich v. Culver City (1996) validated the program against Takings challenges. Includes 3-year aggregation rule against project-splitting. <$75K threshold makes in-lieu mandatory.",
    },
    {
        "id": 23,
        "region": "LA County core",
        "jurisdiction": "Glendale",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "Urban Art Program",
        "reg_type": "1",
        "code_citation": "GMC Title 30 Ch. 30.37; Ord. 5721 (2010); amended 2013, 2014",
        "adopted_effective": "Original 2010",
        "mandatory": "Yes",
        "trigger_scope": "Private development",
        "threshold": "$500,000+",
        "project_types_covered": "Specific commercial zones only (DSP, IMU, IMU-R, SFMU, C1-3, CR, MS, CPD, CH, CA); residential and industrial zones EXCLUDED",
        "on_site_rate": "2% (split-rate)",
        "in_lieu_rate": "1%",
        "fee_cap": "None",
        "compliance_options": "On-site (2%) OR in-lieu (1%)",
        "exemptions": "Residential and industrial zones entirely excluded; City CIP excluded",
        "administrator_fund": "Glendale Arts and Culture Commission",
        "layered_with": None,
        "source_url": "glendaleca.gov",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Stable",
        "confidence": "Confirmed by code",
        "notes": "NARROWEST coverage among LA-core ordinances. Residential and industrial zones entirely excluded. Two-rate structure: 2% on-site / 1% in-lieu.",
    },
    {
        "id": 24,
        "region": "LA County core",
        "jurisdiction": "Inglewood",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "Public Art Program — Municipal (CIP)",
        "reg_type": "1",
        "code_citation": "2011 program (specific code citation to verify)",
        "adopted_effective": "2011",
        "mandatory": "Yes",
        "trigger_scope": "Public CIP",
        "threshold": "Government building projects — rate/threshold to verify",
        "project_types_covered": "City government facilities",
        "on_site_rate": "To verify",
        "in_lieu_rate": "To verify",
        "fee_cap": None,
        "compliance_options": "Commissioned public art",
        "exemptions": None,
        "administrator_fund": "Inglewood Parks, Recreation, and Community Services",
        "layered_with": "Public capital improvement program",
        "source_url": "cityofinglewood.org",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Specific rate/threshold to verify",
        "confidence": "Open item — pending",
        "notes": "Public-side companion to the private development program. Needs direct confirmation of rate and threshold.",
    },
    {
        "id": 25,
        "region": "LA County core",
        "jurisdiction": "Inglewood",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "Public Art Program — Private Development",
        "reg_type": "1",
        "code_citation": "IMC Article 14 (Public Art for New Construction); original May 2004; current procedures Ord. 11-12 (11/8/2011)",
        "adopted_effective": "Original 2004; updated 2011",
        "mandatory": "Yes",
        "trigger_scope": "Private development",
        "threshold": "Non-residential $250,000+",
        "project_types_covered": "Non-residential",
        "on_site_rate": "Historically 1%; current IMC Article 14 references Master Fee Schedule",
        "in_lieu_rate": "Historically 1%; current IMC Article 14 references Master Fee Schedule",
        "fee_cap": "Verify current Master Fee Schedule",
        "compliance_options": "Donate / install / in-lieu",
        "exemptions": "Per code",
        "administrator_fund": "Inglewood Parks, Recreation, and Community Services Department",
        "layered_with": "Significant given SoFi Stadium / Intuit Dome corridor transformation; CBAs pending follow-up",
        "source_url": "https://ecode360.com/43784253",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Current rate depends on Master Fee Schedule — verify directly. SoFi/Intuit Dome era likely produced major Type 4 CBAs — pending follow-up.",
        "confidence": "Secondary source only",
        "notes": "Current code specifies art 'valued as specified in the Master Fee Schedule' rather than a percentage. Historical 2004/2011 sources support 1%. Significant relevance given SoFi Stadium, Intuit Dome, LA Clippers practice facility.",
    },
    {
        "id": 26,
        "region": "LA County core",
        "jurisdiction": "Long Beach",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "Measure B — Transient Occupancy Tax for Arts",
        "reg_type": "1",
        "code_citation": "Measure B (2020 ballot)",
        "adopted_effective": "2020",
        "mandatory": "Yes (TOT)",
        "trigger_scope": "TOT (hotel/short-term lodging)",
        "threshold": "All hotel/lodging revenue",
        "project_types_covered": "Lodging",
        "on_site_rate": None,
        "in_lieu_rate": "1% of TOT",
        "fee_cap": "None",
        "compliance_options": None,
        "exemptions": None,
        "administrator_fund": "Arts Council for Long Beach (grants)",
        "layered_with": "Operates alongside AR 9-1 for private development",
        "source_url": "longbeach.gov",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Stable",
        "confidence": "Secondary source only",
        "notes": "Distinctive revenue mechanism — funded by lodging tax rather than development fees. Funds Arts Council grants, not direct public art commissions.",
    },
    {
        "id": 27,
        "region": "LA County core",
        "jurisdiction": "Long Beach",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "Percent for Arts — Administrative Regulation 9-1",
        "reg_type": "1",
        "code_citation": "Administrative Regulation 9-1 (NOT codified ordinance); Council action 12/20/2016",
        "adopted_effective": "12/20/2016 Council action",
        "mandatory": "Yes (administrative regulation)",
        "trigger_scope": "Public CIP",
        "threshold": "City-managed capital construction projects over $100,000",
        "project_types_covered": "City-managed capital construction projects only — does NOT apply to private development",
        "on_site_rate": "1% of project cost",
        "in_lieu_rate": None,
        "fee_cap": "$500,000 per project",
        "compliance_options": "1% assessment on eligible City capital construction projects; cap limits exposure on large projects",
        "exemptions": "Per regulation",
        "administrator_fund": "Arts Council for Long Beach (independent nonprofit)",
        "layered_with": "Measure B (separate TOT revenue stream)",
        "source_url": "https://www.longbeach.gov/citymanager/offices-and-services/arts-support/",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "UNDER REVIEW for expansion (Council motion 3/18/2025); through 2024 collected ~$1.35M total",
        "confidence": "Confirmed by city page",
        "notes": "PUBLIC CIP ONLY — does not apply to private development. Long Beach currently has NO mandatory percent-for-art ordinance for private development. Administered by Arts Council for Long Beach as an independent nonprofit.",
    },
    {
        "id": 28,
        "region": "LA County core",
        "jurisdiction": "Pasadena",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "Public Art Master Plan — Private Development Program",
        "reg_type": "2",
        "code_citation": "Master Plan adopted 10/21/2013",
        "adopted_effective": "Master Plan 10/21/2013",
        "mandatory": "Yes",
        "trigger_scope": "Private development",
        "threshold": "Citywide: 25,000+ sqft commercial/industrial/mixed-use/parking; Northwest Boundary Area: $500K+; Downtown/Old Pasadena Redevelopment Areas: $500K+",
        "project_types_covered": "Commercial, industrial, mixed-use, parking",
        "on_site_rate": "≥1%",
        "in_lieu_rate": "≥1%",
        "fee_cap": "None",
        "compliance_options": "On-site OR in-lieu; cultural facilities may satisfy requirement",
        "exemptions": "Per plan",
        "administrator_fund": "Pasadena Cultural Affairs Division",
        "layered_with": "Private + CIP (separate companion program); Type 3 Specific Plans pending follow-up",
        "source_url": "cityofpasadena.net",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Stable; CIP details pending follow-up",
        "confidence": "Confirmed by city page",
        "notes": "Notable for GEOGRAPHIC VARIANCE — three different thresholds depending on location within the city. Cultural facilities can satisfy the requirement (broader compliance option than typical).",
    },
    {
        "id": 29,
        "region": "LA County core",
        "jurisdiction": "Santa Monica",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "Private Developer Cultural Arts Requirement",
        "reg_type": "1",
        "code_citation": "SMMC Ch. 9.30; Ord. 2486CCS (6/23/2015); original program 2006",
        "adopted_effective": "Original 2006; current 6/23/2015",
        "mandatory": "Yes",
        "trigger_scope": "Private development",
        "threshold": "New construction 7,500+ sqft; commercial remodel 25,000+ sqft; residential 5+ units",
        "project_types_covered": "Commercial, mixed-use, residential 5+ units",
        "on_site_rate": "2% (split-rate to incentivize on-site)",
        "in_lieu_rate": "1%",
        "fee_cap": "None",
        "compliance_options": "On-site (2%) OR in-lieu (1%)",
        "exemptions": "Adaptive reuse per Ch. 9.31.035; affordable units excluded from calc",
        "administrator_fund": "Santa Monica Cultural Affairs",
        "layered_with": "Bergamot Specific Plan, Downtown Community Plan (Type 3 follow-up)",
        "source_url": "santamonica.gov municipal code",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Stable",
        "confidence": "Confirmed by code",
        "notes": "Two-rate structure: on-site 2%, in-lieu 1%. Adaptive reuse exemption is distinctive given Santa Monica's commercial inventory.",
    },
    {
        "id": 30,
        "region": "LA County core",
        "jurisdiction": "West Hollywood",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "Urban Art Program",
        "reg_type": "1",
        "code_citation": "WHMC Ch. 19.38; Ord. 01-594 (2001); amended 14-940, 19-1058",
        "adopted_effective": "Original 2001",
        "mandatory": "Yes",
        "trigger_scope": "Private development",
        "threshold": "Project valuation $200,000+ (LOWEST in LA core); residential 3+ units triggers",
        "project_types_covered": "Commercial, mixed-use, residential 3+ units",
        "on_site_rate": "1%",
        "in_lieu_rate": "1%",
        "fee_cap": "None",
        "compliance_options": "On-site urban art OR in-lieu; mandatory pre-approved Art Consultant",
        "exemptions": "Per code",
        "administrator_fund": "West Hollywood Arts Division",
        "layered_with": None,
        "source_url": "weho.org",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Stable",
        "confidence": "Confirmed by code",
        "notes": "LOWEST threshold in LA core ($200K) and broadest residential trigger (3+ units vs. typical 5+). Mandatory pre-approved Art Consultant is distinctive.",
    },
    {
        "id": 31,
        "region": "LA County secondary",
        "jurisdiction": "Calabasas",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "Art in Public Places",
        "reg_type": "1",
        "code_citation": "Calabasas Municipal Code (Art in Public Places provisions)",
        "adopted_effective": None,
        "mandatory": "Yes",
        "trigger_scope": "Private development",
        "threshold": "All commercial construction and reconstruction projects",
        "project_types_covered": "Commercial",
        "on_site_rate": "1% of building valuation",
        "in_lieu_rate": "1% to Art in Public Places Fund",
        "fee_cap": "$150,000 maximum (LOWEST in LA-area survey)",
        "compliance_options": "On-site installation OR in-lieu fee; City Council approves artwork prior to CofO",
        "exemptions": "Per code",
        "administrator_fund": "Art in Public Places Advisory Committee",
        "layered_with": None,
        "source_url": "https://www.cityofcalabasas.com/government/commissions/art-in-public-places-advisory-committee",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Stable",
        "confidence": "Confirmed by city page",
        "notes": "LOWEST CAP in LA-area survey ($150K). For a hypothetical $30M project, obligation caps at $150K rather than uncapped $300K. Cap dramatically changes project economics.",
    },
    {
        "id": 32,
        "region": "LA County secondary",
        "jurisdiction": "El Segundo",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "Cultural Development Fee",
        "reg_type": "1",
        "code_citation": "ESMC § 15-34; Ord. 1594 (11/19/2019); amended 4/1/2025",
        "adopted_effective": "Original 11/19/2019; amended 4/1/2025",
        "mandatory": "Yes",
        "trigger_scope": "Private development",
        "threshold": "Commercial and industrial $2,000,000+ (HIGH threshold — 4x LA-area baseline)",
        "project_types_covered": "Commercial, industrial only",
        "on_site_rate": "1%",
        "in_lieu_rate": "1% to Cultural Development Fund",
        "fee_cap": "$1,000,000 (per April 2025 amendment)",
        "compliance_options": "On-site / in-lieu / split between (split allowed per April 2025 amendment)",
        "exemptions": "Residential excluded",
        "administrator_fund": "Arts and Culture Advisory Committee",
        "layered_with": None,
        "source_url": "https://www.elsegundolibrary.org/about-us/cultural-development-program-268521",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Recent April 2025 amendment — fee cap, split allowance, CofO timing",
        "confidence": "Confirmed by city page",
        "notes": "$2M threshold is one of the highest in LA County. April 2025 amendment introduced: (a) split between on-site and in-lieu, (b) $1M fee cap, (c) payment due at certificate of occupancy.",
    },
    {
        "id": 33,
        "region": "LA County secondary",
        "jurisdiction": "Hawthorne",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "NO mandatory percent-for-art ordinance surfaced",
        "reg_type": None,
        "code_citation": None,
        "adopted_effective": None,
        "mandatory": "No (not surfaced)",
        "trigger_scope": None,
        "threshold": None,
        "project_types_covered": None,
        "on_site_rate": None,
        "in_lieu_rate": None,
        "fee_cap": None,
        "compliance_options": None,
        "exemptions": None,
        "administrator_fund": None,
        "layered_with": None,
        "source_url": None,
        "date_verified": "2026-05-13",
        "currency_risk_flags": None,
        "confidence": None,
        "notes": None,
    },

    {
        "id": 34,
        "region": "LA County secondary",
        "jurisdiction": "Malibu",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "Art in Public Places Ordinance",
        "reg_type": "1",
        "code_citation": "MMC Ch. 17.59; adopted 9/8/2014; effective 10/22/2014",
        "adopted_effective": "Effective 10/22/2014",
        "mandatory": "Yes",
        "trigger_scope": "Private development",
        "threshold": "Per 2014 staff report: commercial/institutional $250K+; multi-family residential 4+ units fronting public street $250K+ (final adopted thresholds to verify directly from codified MMC Ch. 17.59)",
        "project_types_covered": "Commercial, institutional, multi-family residential 4+ units",
        "on_site_rate": "To verify (typical 1%)",
        "in_lieu_rate": "To verify",
        "fee_cap": None,
        "compliance_options": "On-site OR in-lieu fee",
        "exemptions": "Per code",
        "administrator_fund": "Malibu Arts Commission (formerly Cultural Arts Commission, renamed Ord. 482 in 2021)",
        "layered_with": None,
        "source_url": "https://malibuartsandculture.org/237/Art-in-Public-Places-Ordinance",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Final adopted rate/threshold to confirm directly from MMC text",
        "confidence": "Open item — pending",
        "notes": "Adopted threshold and rate need verification from the actual codified Chapter 17.59 — the 2014 staff report described the proposal. Implementation administered by Arts Commission with public art review.",
    },
    {
        "id": 35,
        "region": "LA County secondary",
        "jurisdiction": "Manhattan Beach",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "Public Arts Fund / Percent for the Arts",
        "reg_type": "1",
        "code_citation": "Ordinance passed 11/19/2002; effective 12/18/2002",
        "adopted_effective": "Effective 12/18/2002",
        "mandatory": "Yes",
        "trigger_scope": "Private development",
        "threshold": "New construction: commercial/industrial/residential 4+ units $500K+; remodel $250K+",
        "project_types_covered": "Commercial, industrial, residential 4+ units",
        "on_site_rate": "1%",
        "in_lieu_rate": "1% to Public Arts Fund",
        "fee_cap": "None",
        "compliance_options": "On-site OR in-lieu",
        "exemptions": "Per code",
        "administrator_fund": "Manhattan Beach Cultural Arts Commission",
        "layered_with": None,
        "source_url": "https://www.manhattanbeach.gov/departments/parks-and-recreation/cultural-arts/art-in-public-places",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Public Art Master Plan revision underway 2025; PATF ordinance revisions possible",
        "confidence": "Confirmed by city page",
        "notes": "Classic LA-area 'vanilla' configuration. Remodel sub-threshold of $250K captures more renovations than typical. Master Plan revision in progress — monitor for changes.",
    },
    {
        "id": 36,
        "region": "LA County secondary",
        "jurisdiction": "Redondo Beach",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "Public Art Requirements",
        "reg_type": "1",
        "code_citation": "RBMC Title 10 Ch. 6; Ord. 3127-14 effective 1/2/2015; amended Ord. 3278-24 effective 10/1/2024",
        "adopted_effective": "Original 1/2/2015; amended 10/1/2024",
        "mandatory": "Yes",
        "trigger_scope": "Both (private development and public CIP)",
        "threshold": "$250,000+ building valuation",
        "project_types_covered": "Private development; public CIP",
        "on_site_rate": "1%",
        "in_lieu_rate": "1% of valuation above $250,000",
        "fee_cap": "None",
        "compliance_options": "On-site / nearby / partial split allowed; architecture-as-art definition is broad (handrails, stained glass, etc.)",
        "exemptions": "Per code",
        "administrator_fund": "Redondo Beach Cultural Arts Commission",
        "layered_with": None,
        "source_url": "https://ecode360.com/42661453",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Recent 2024 amendment refreshed administrative provisions",
        "confidence": "Confirmed by code",
        "notes": "Among the lower thresholds in LA County. Broad architecture-as-art definition (decorative handrails, stained glass, functional features enhanced to be visually appealing) is more permissive than most ordinances.",
    },
    {
        "id": 37,
        "region": "LA County secondary",
        "jurisdiction": "Torrance",
        "type": "city",
        "county": "Los Angeles",
        "program_name": "NO mandatory percent-for-art ordinance",
        "reg_type": None,
        "code_citation": None,
        "adopted_effective": None,
        "mandatory": "No",
        "trigger_scope": None,
        "threshold": None,
        "project_types_covered": None,
        "on_site_rate": None,
        "in_lieu_rate": None,
        "fee_cap": None,
        "compliance_options": None,
        "exemptions": None,
        "administrator_fund": "Cultural Arts Commission (advisory); Cultural Services Division (city programs)",
        "layered_with": None,
        "source_url": "https://www.torranceca.gov/services/cultural-services-division-arts-and-classes/public-art",
        "date_verified": "2026-05-13",
        "currency_risk_flags": None,
        "confidence": "Confirmed by city page",
        "notes": "City's own page states: 'Although Torrance does not have a formal Percent for Art policy, the City has commissioned artists for site specific work and accepted donations of artwork.' Significant gap — Torrance is the third-largest South Bay city (~143K). Public art exists via city commission, donation, or voluntary developer choice only.",
    },
    {
        "id": 38,
        "region": "Orange County",
        "jurisdiction": "Anaheim",
        "type": "city",
        "county": "Orange",
        "program_name": "Public Art Plan (Ch. 17.37) — NOT a mandatory percent-for-art",
        "reg_type": None,
        "code_citation": "AMC Ch. 17.37 (Ord. 6451); Mural Program AMC § 18.62.130",
        "adopted_effective": "Adopted by City Council via Ord. 6451",
        "mandatory": "No (promotional)",
        "trigger_scope": "City programs + privately-commissioned murals via permit",
        "threshold": None,
        "project_types_covered": "City projects; Mural Program for privately-commissioned murals",
        "on_site_rate": None,
        "in_lieu_rate": None,
        "fee_cap": None,
        "compliance_options": None,
        "exemptions": None,
        "administrator_fund": "Cultural and Heritage Commission (advisory); Interdepartmental Public Art Coordination Committee (IPACC)",
        "layered_with": None,
        "source_url": "https://local.anaheim.net/docs_agend/questys_pub/41761/41791/41792/41825/41992/1.%20Public%20Art%20Guidelines41992.pdf",
        "date_verified": "2026-05-13",
        "currency_risk_flags": None,
        "confidence": "Confirmed by code",
        "notes": "Ordinance is a Public Art PLAN (promotional/encouraging) rather than a mandatory percent-for-art fee. Mural Program is a permit-fee program for privately-commissioned murals, not a percent of project valuation. Significant gap: Anaheim is the largest OC city (~350K residents) yet has no mandatory developer percent-for-art.",
    },
    {
        "id": 39,
        "region": "Orange County",
        "jurisdiction": "Brea",
        "type": "city",
        "county": "Orange",
        "program_name": "Art in Public Places (APP) Program",
        "reg_type": "2",
        "code_citation": "Brea Code Zoning § 20.408.040(C)(4); codified by Ord. 1050 (2001); APP Manual Resolution 2021-066 (11/2/2021); program established 1975",
        "adopted_effective": "Program established 1975; first Resolution 84-143 (1984); codified by Ord. 1050 (2001); current APP Manual 2021",
        "mandatory": "Yes",
        "trigger_scope": "Private development",
        "threshold": "Developments valued at $1,500,000 or more",
        "project_types_covered": "Per zoning code",
        "on_site_rate": "1% of total project value",
        "in_lieu_rate": "1% to Brea's Art Fund (available only at $1.5M–$3.99M tier)",
        "fee_cap": "None",
        "compliance_options": "$1.5M–$3,999,999: install approved publicly visible sculpture OR contribute to Brea's Art Fund in-lieu (developer choice); $4,000,000+: must install on-site sculpture (no in-lieu option)",
        "exemptions": "Per APP Policy Manual",
        "administrator_fund": "Brea APP Advisory Committee; Brea Cultural Arts Division; Brea's Art Fund",
        "layered_with": None,
        "source_url": "https://www.cityofbrea.gov/202/Sculpture-Requirement-for-Developers",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "APP Manual updated 2021",
        "confidence": "Confirmed by city page",
        "notes": "One of California's earliest public art programs (1975), pre-dating Ehrlich v. Culver City (1996) by two decades. SCULPTURE-SPECIFIC focus is distinctive. Tiered compliance: smaller projects ($1.5M–$3.99M) have the in-lieu option; larger projects ($4M+) must install on-site sculpture. 185+ sculptures in a 12.43-square-mile city.",
    },
    {
        "id": 40,
        "region": "Orange County",
        "jurisdiction": "Costa Mesa",
        "type": "city",
        "county": "Orange",
        "program_name": "Public Art Program (city-driven) — NOT a mandatory percent-for-art",
        "reg_type": None,
        "code_citation": "Arts and Culture Master Plan; Art in Public Places Report (Apr 2023, Arts Orange County consultant)",
        "adopted_effective": "Master Plan and reports ongoing",
        "mandatory": "No",
        "trigger_scope": "City programs only",
        "threshold": None,
        "project_types_covered": None,
        "on_site_rate": None,
        "in_lieu_rate": None,
        "fee_cap": None,
        "compliance_options": None,
        "exemptions": None,
        "administrator_fund": "Costa Mesa Arts Commission; Parks and Community Services",
        "layered_with": None,
        "source_url": "https://www.costamesaca.gov/government/departments-and-divisions/parks-and-community-services/arts-culture/public-art",
        "date_verified": "2026-05-13",
        "currency_risk_flags": None,
        "confidence": "Confirmed by city page",
        "notes": "Costa Mesa is the OC arts-and-culture epicenter (Segerstrom Center for the Arts, South Coast Repertory, OCMA's new home) — yet operates without a mandatory developer fee. Utility Box Art Program (60+ designs since 2015). Costa Mesa Art Walk near Segerstrom is private/voluntary curation.",
    },
    {
        "id": 41,
        "region": "Orange County",
        "jurisdiction": "Huntington Beach",
        "type": "city",
        "county": "Orange",
        "program_name": "Public art program — no clear mandatory percent-for-art for private development",
        "reg_type": None,
        "code_citation": None,
        "adopted_effective": None,
        "mandatory": "No (not clearly surfaced)",
        "trigger_scope": None,
        "threshold": None,
        "project_types_covered": None,
        "on_site_rate": None,
        "in_lieu_rate": None,
        "fee_cap": None,
        "compliance_options": None,
        "exemptions": None,
        "administrator_fund": "Huntington Beach Art Center (Senior Cultural Arts Supervisor: Dan Faltz)",
        "layered_with": "Possible Specific Plan / development agreement conditions for Pacific City",
        "source_url": "huntingtonbeachca.gov",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Pacific City Specific Plan may contain arts conditions — pending verification",
        "confidence": "Negative — needs staff call",
        "notes": "43 pieces of public art (Duke Kahanamoku statue, etc.); Surf City identity drives thematic public art. Pacific City development includes substantial private public-art investment (Paséa Hotel & Spa murals) — possibly voluntary, possibly negotiated as Specific Plan or development agreement condition.",
    },
    {
        "id": 42,
        "region": "Orange County",
        "jurisdiction": "Irvine",
        "type": "city",
        "county": "Orange",
        "program_name": "NO mandatory percent-for-art ordinance surfaced",
        "reg_type": None,
        "code_citation": None,
        "adopted_effective": None,
        "mandatory": "No (not surfaced)",
        "trigger_scope": None,
        "threshold": None,
        "project_types_covered": None,
        "on_site_rate": None,
        "in_lieu_rate": None,
        "fee_cap": None,
        "compliance_options": None,
        "exemptions": None,
        "administrator_fund": "City Arts Commission (advisory)",
        "layered_with": None,
        "source_url": None,
        "date_verified": "2026-05-13",
        "currency_risk_flags": None,
        "confidence": "Negative — needs staff call",
        "notes": "Significant gap: Irvine is OC's second-largest city (~310K residents) with major employment centers (Spectrum, Business Complex, UCI). UC Irvine campus has substantial public art; Irvine Great Park has rotating exhibitions. These are institution-driven and city-driven, not developer-triggered. The Irvine Company as master developer has historically commissioned art voluntarily, but this is not codified.",
    },
    {
        "id": 43,
        "region": "Orange County",
        "jurisdiction": "Laguna Beach",
        "type": "city",
        "county": "Orange",
        "program_name": "Art in Public Places Program",
        "reg_type": "1",
        "code_citation": "Laguna Beach Code Title 1 Ch. 1.09; Ord. 1119 (1986); amended Ord. 1210 (1991), Ord. 1700 (6/11/2024)",
        "adopted_effective": "Original 1986; current amendment 6/11/2024",
        "mandatory": "Yes",
        "trigger_scope": "Both (city public works AND private development)",
        "threshold": "$225,000+ (one of the lowest surveyed)",
        "project_types_covered": "City public works (bridges, viaducts, parks, etc.); private development at parallel threshold",
        "on_site_rate": "1%",
        "in_lieu_rate": "1%",
        "fee_cap": "None",
        "compliance_options": "On-site OR in-lieu",
        "exemptions": "Remodeling/repair after fire/flood/wind/earthquake; nonprofit social service agency or institution structures",
        "administrator_fund": "Laguna Beach Cultural Arts; Arts Commission",
        "layered_with": None,
        "source_url": "https://ecode360.com/42882939",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Recent June 2024 amendment — verify scope of changes",
        "confidence": "Confirmed by code",
        "notes": "$225K is one of the lowest thresholds surveyed (matched only by Manhattan Beach $250K remodel and Redondo Beach $250K). Laguna Beach's identity as an 'art colony' is embedded in the ordinance preamble. Recently amended June 2024.",
    },
    {
        "id": 44,
        "region": "Orange County",
        "jurisdiction": "Newport Beach",
        "type": "city",
        "county": "Orange",
        "program_name": "NO mandatory percent-for-art ordinance",
        "reg_type": None,
        "code_citation": None,
        "adopted_effective": None,
        "mandatory": "No",
        "trigger_scope": None,
        "threshold": None,
        "project_types_covered": None,
        "on_site_rate": None,
        "in_lieu_rate": None,
        "fee_cap": None,
        "compliance_options": None,
        "exemptions": None,
        "administrator_fund": "City Arts Commission",
        "layered_with": None,
        "source_url": "newportbeachca.gov",
        "date_verified": "2026-05-13",
        "currency_risk_flags": None,
        "confidence": "Confirmed by city page",
        "notes": "Newport Beach's program is the Sculpture in Civic Center Park Exhibition — a rotating exhibition where pieces return to artists after ~2 years. No developer-triggered requirement. Despite affluent demographics (Fashion Island, harbor, Civic Center Park), no developer mechanism.",
    },
    {
        "id": 45,
        "region": "Orange County",
        "jurisdiction": "Santa Ana",
        "type": "city",
        "county": "Orange",
        "program_name": "NO mandatory percent-for-art ordinance surfaced",
        "reg_type": None,
        "code_citation": None,
        "adopted_effective": None,
        "mandatory": "No (not surfaced)",
        "trigger_scope": None,
        "threshold": None,
        "project_types_covered": None,
        "on_site_rate": None,
        "in_lieu_rate": None,
        "fee_cap": None,
        "compliance_options": None,
        "exemptions": None,
        "administrator_fund": "City Arts Commission",
        "layered_with": None,
        "source_url": "santa-ana.org",
        "date_verified": "2026-05-13",
        "currency_risk_flags": "Recommend direct verification with Community Development",
        "confidence": "Negative — needs staff call",
        "notes": "Santa Ana is the OC County Seat (~330K residents) with a robust arts ecosystem: Artists Village (10-block district), Grand Central Art Center (Cal State Fullerton), Second Street Promenade, monthly First Saturday ArtWalk. These are largely organic / nonprofit-driven. Lacks the development-side regulatory mechanism present in LA city.",
    },
]


def seed():
    conn = sqlite3.connect(DB_PATH)
    try:
        conn.executescript(SCHEMA_SQL)
        placeholders = ", ".join(f":{col}" for col in COLUMNS)
        sql = f"INSERT INTO regulations ({', '.join(COLUMNS)}) VALUES ({placeholders})"
        conn.executemany(sql, RECORDS)
        conn.commit()
        print(f"Seeded {len(RECORDS)} records into {DB_PATH}")
    finally:
        conn.close()


if __name__ == "__main__":
    seed()
